#!/usr/bin/env bash

# --------------------------------------------------------------------------------

# print a line across the console of a character $1
function lineof() {
  printf "%.s$1" $(seq 1 $(tput cols))
}

# print text $1 in bold
function becho() {
  BOLD=$(tput bold)
  REGULAR=$(tput sgr0)
  echo "$BOLD$1$REGULAR"
}

# --------------------------------------------------------------------------------

src=$1
verbosity=0

# parse flags
for arg in "$@"; do
  case $arg in
    -v=*|--verbosity=*)
      verbosity="${arg#*=}"
    ;;
  esac
done

# strip blank lines from source
s="$(cat "$src" | grep ".")"

# apply preprocessor until the text doesn't change
i=0
while : ; do
  if [ "$verbosity" -gt "0" ]; then
    lineof "─"
    becho "Pass $i"
    lineof "─"
    let i++
    if [ "$verbosity" -gt "1" ]; then
      echo "$s"
    fi
  fi

  #pp="cpp -D __FILE__=\"$1\""
  pp="cpp"

  # run one pass of the preprocessor
  # grep is used exclude remarks (e.g. # 1 "<stdin>") and empty lines added by cpp
  if [ "$verbosity" -gt "0" ]; then
    new="$(echo "$s" | $pp | grep "." | grep -v "^# ")"
  else
    new="$(echo "$s" | $pp 2> /dev/null | grep "." | grep -v "^# ")"
  fi

  if [ "$new" == "$s" ]; then break; fi
  s="$new"
done

# print output
if [ "$verbosity" -gt "0" ]; then
  lineof "─"
  becho "Output (after $i passes)"
  lineof "─"
fi
echo "$s"

