/*
  Inputs: None
  Pops the bit from the top of the stack into ITEM.
*/
#include "util.h"
IFDEF STACK_0
  DEFINE ARG1() ITEM
  DEFINE ARG2() STACK_0
  INCLUDE "movb.h"
  UNDEF STACK_0
ELSE
IFDEF STACK_1
  DEFINE ARG1() ITEM
  DEFINE ARG2() STACK_1
  INCLUDE "movb.h"
  UNDEF STACK_1
ELSE
IFDEF STACK_2
  DEFINE ARG1() ITEM
  DEFINE ARG2() STACK_2
  INCLUDE "movb.h"
  UNDEF STACK_2
ELSE
IFDEF STACK_3
  DEFINE ARG1() ITEM
  DEFINE ARG2() STACK_3
  INCLUDE "movb.h"
  UNDEF STACK_3
ELSE
IFDEF STACK_4
  DEFINE ARG1() ITEM
  DEFINE ARG2() STACK_4
  INCLUDE "movb.h"
  UNDEF STACK_4
ELSE
IFDEF STACK_5
  DEFINE ARG1() ITEM
  DEFINE ARG2() STACK_5
  INCLUDE "movb.h"
  UNDEF STACK_5
ELSE
IFDEF STACK_6
  DEFINE ARG1() ITEM
  DEFINE ARG2() STACK_6
  INCLUDE "movb.h"
  UNDEF STACK_6
ELSE
IFDEF STACK_7
  DEFINE ARG1() ITEM
  DEFINE ARG2() STACK_7
  INCLUDE "movb.h"
  UNDEF STACK_7
ELSE
IFDEF STACK_8
  DEFINE ARG1() ITEM
  DEFINE ARG2() STACK_8
  INCLUDE "movb.h"
  UNDEF STACK_8
ELSE
IFDEF STACK_9
  DEFINE ARG1() ITEM
  DEFINE ARG2() STACK_9
  INCLUDE "movb.h"
  UNDEF STACK_9
ELSE
  ERROR Stack underflow
END
END
END
END
END
END
END
END
END
END
