/*
  Pushes the item ITEM onto the stack.
*/
#include "util.h"
IFNDEF STACK_499
  DEFINE ARG1 STACK_499
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_498
  DEFINE ARG1 STACK_498
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_497
  DEFINE ARG1 STACK_497
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_496
  DEFINE ARG1 STACK_496
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_495
  DEFINE ARG1 STACK_495
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_494
  DEFINE ARG1 STACK_494
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_493
  DEFINE ARG1 STACK_493
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_492
  DEFINE ARG1 STACK_492
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_491
  DEFINE ARG1 STACK_491
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_490
  DEFINE ARG1 STACK_490
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_489
  DEFINE ARG1 STACK_489
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_488
  DEFINE ARG1 STACK_488
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_487
  DEFINE ARG1 STACK_487
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_486
  DEFINE ARG1 STACK_486
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_485
  DEFINE ARG1 STACK_485
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_484
  DEFINE ARG1 STACK_484
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_483
  DEFINE ARG1 STACK_483
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_482
  DEFINE ARG1 STACK_482
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_481
  DEFINE ARG1 STACK_481
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_480
  DEFINE ARG1 STACK_480
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_479
  DEFINE ARG1 STACK_479
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_478
  DEFINE ARG1 STACK_478
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_477
  DEFINE ARG1 STACK_477
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_476
  DEFINE ARG1 STACK_476
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_475
  DEFINE ARG1 STACK_475
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_474
  DEFINE ARG1 STACK_474
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_473
  DEFINE ARG1 STACK_473
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_472
  DEFINE ARG1 STACK_472
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_471
  DEFINE ARG1 STACK_471
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_470
  DEFINE ARG1 STACK_470
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_469
  DEFINE ARG1 STACK_469
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_468
  DEFINE ARG1 STACK_468
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_467
  DEFINE ARG1 STACK_467
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_466
  DEFINE ARG1 STACK_466
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_465
  DEFINE ARG1 STACK_465
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_464
  DEFINE ARG1 STACK_464
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_463
  DEFINE ARG1 STACK_463
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_462
  DEFINE ARG1 STACK_462
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_461
  DEFINE ARG1 STACK_461
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_460
  DEFINE ARG1 STACK_460
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_459
  DEFINE ARG1 STACK_459
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_458
  DEFINE ARG1 STACK_458
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_457
  DEFINE ARG1 STACK_457
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_456
  DEFINE ARG1 STACK_456
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_455
  DEFINE ARG1 STACK_455
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_454
  DEFINE ARG1 STACK_454
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_453
  DEFINE ARG1 STACK_453
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_452
  DEFINE ARG1 STACK_452
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_451
  DEFINE ARG1 STACK_451
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_450
  DEFINE ARG1 STACK_450
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_449
  DEFINE ARG1 STACK_449
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_448
  DEFINE ARG1 STACK_448
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_447
  DEFINE ARG1 STACK_447
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_446
  DEFINE ARG1 STACK_446
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_445
  DEFINE ARG1 STACK_445
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_444
  DEFINE ARG1 STACK_444
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_443
  DEFINE ARG1 STACK_443
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_442
  DEFINE ARG1 STACK_442
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_441
  DEFINE ARG1 STACK_441
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_440
  DEFINE ARG1 STACK_440
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_439
  DEFINE ARG1 STACK_439
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_438
  DEFINE ARG1 STACK_438
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_437
  DEFINE ARG1 STACK_437
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_436
  DEFINE ARG1 STACK_436
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_435
  DEFINE ARG1 STACK_435
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_434
  DEFINE ARG1 STACK_434
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_433
  DEFINE ARG1 STACK_433
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_432
  DEFINE ARG1 STACK_432
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_431
  DEFINE ARG1 STACK_431
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_430
  DEFINE ARG1 STACK_430
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_429
  DEFINE ARG1 STACK_429
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_428
  DEFINE ARG1 STACK_428
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_427
  DEFINE ARG1 STACK_427
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_426
  DEFINE ARG1 STACK_426
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_425
  DEFINE ARG1 STACK_425
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_424
  DEFINE ARG1 STACK_424
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_423
  DEFINE ARG1 STACK_423
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_422
  DEFINE ARG1 STACK_422
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_421
  DEFINE ARG1 STACK_421
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_420
  DEFINE ARG1 STACK_420
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_419
  DEFINE ARG1 STACK_419
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_418
  DEFINE ARG1 STACK_418
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_417
  DEFINE ARG1 STACK_417
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_416
  DEFINE ARG1 STACK_416
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_415
  DEFINE ARG1 STACK_415
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_414
  DEFINE ARG1 STACK_414
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_413
  DEFINE ARG1 STACK_413
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_412
  DEFINE ARG1 STACK_412
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_411
  DEFINE ARG1 STACK_411
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_410
  DEFINE ARG1 STACK_410
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_409
  DEFINE ARG1 STACK_409
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_408
  DEFINE ARG1 STACK_408
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_407
  DEFINE ARG1 STACK_407
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_406
  DEFINE ARG1 STACK_406
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_405
  DEFINE ARG1 STACK_405
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_404
  DEFINE ARG1 STACK_404
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_403
  DEFINE ARG1 STACK_403
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_402
  DEFINE ARG1 STACK_402
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_401
  DEFINE ARG1 STACK_401
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_400
  DEFINE ARG1 STACK_400
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_399
  DEFINE ARG1 STACK_399
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_398
  DEFINE ARG1 STACK_398
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_397
  DEFINE ARG1 STACK_397
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_396
  DEFINE ARG1 STACK_396
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_395
  DEFINE ARG1 STACK_395
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_394
  DEFINE ARG1 STACK_394
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_393
  DEFINE ARG1 STACK_393
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_392
  DEFINE ARG1 STACK_392
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_391
  DEFINE ARG1 STACK_391
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_390
  DEFINE ARG1 STACK_390
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_389
  DEFINE ARG1 STACK_389
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_388
  DEFINE ARG1 STACK_388
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_387
  DEFINE ARG1 STACK_387
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_386
  DEFINE ARG1 STACK_386
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_385
  DEFINE ARG1 STACK_385
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_384
  DEFINE ARG1 STACK_384
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_383
  DEFINE ARG1 STACK_383
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_382
  DEFINE ARG1 STACK_382
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_381
  DEFINE ARG1 STACK_381
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_380
  DEFINE ARG1 STACK_380
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_379
  DEFINE ARG1 STACK_379
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_378
  DEFINE ARG1 STACK_378
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_377
  DEFINE ARG1 STACK_377
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_376
  DEFINE ARG1 STACK_376
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_375
  DEFINE ARG1 STACK_375
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_374
  DEFINE ARG1 STACK_374
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_373
  DEFINE ARG1 STACK_373
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_372
  DEFINE ARG1 STACK_372
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_371
  DEFINE ARG1 STACK_371
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_370
  DEFINE ARG1 STACK_370
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_369
  DEFINE ARG1 STACK_369
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_368
  DEFINE ARG1 STACK_368
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_367
  DEFINE ARG1 STACK_367
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_366
  DEFINE ARG1 STACK_366
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_365
  DEFINE ARG1 STACK_365
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_364
  DEFINE ARG1 STACK_364
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_363
  DEFINE ARG1 STACK_363
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_362
  DEFINE ARG1 STACK_362
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_361
  DEFINE ARG1 STACK_361
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_360
  DEFINE ARG1 STACK_360
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_359
  DEFINE ARG1 STACK_359
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_358
  DEFINE ARG1 STACK_358
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_357
  DEFINE ARG1 STACK_357
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_356
  DEFINE ARG1 STACK_356
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_355
  DEFINE ARG1 STACK_355
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_354
  DEFINE ARG1 STACK_354
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_353
  DEFINE ARG1 STACK_353
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_352
  DEFINE ARG1 STACK_352
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_351
  DEFINE ARG1 STACK_351
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_350
  DEFINE ARG1 STACK_350
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_349
  DEFINE ARG1 STACK_349
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_348
  DEFINE ARG1 STACK_348
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_347
  DEFINE ARG1 STACK_347
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_346
  DEFINE ARG1 STACK_346
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_345
  DEFINE ARG1 STACK_345
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_344
  DEFINE ARG1 STACK_344
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_343
  DEFINE ARG1 STACK_343
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_342
  DEFINE ARG1 STACK_342
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_341
  DEFINE ARG1 STACK_341
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_340
  DEFINE ARG1 STACK_340
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_339
  DEFINE ARG1 STACK_339
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_338
  DEFINE ARG1 STACK_338
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_337
  DEFINE ARG1 STACK_337
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_336
  DEFINE ARG1 STACK_336
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_335
  DEFINE ARG1 STACK_335
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_334
  DEFINE ARG1 STACK_334
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_333
  DEFINE ARG1 STACK_333
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_332
  DEFINE ARG1 STACK_332
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_331
  DEFINE ARG1 STACK_331
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_330
  DEFINE ARG1 STACK_330
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_329
  DEFINE ARG1 STACK_329
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_328
  DEFINE ARG1 STACK_328
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_327
  DEFINE ARG1 STACK_327
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_326
  DEFINE ARG1 STACK_326
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_325
  DEFINE ARG1 STACK_325
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_324
  DEFINE ARG1 STACK_324
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_323
  DEFINE ARG1 STACK_323
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_322
  DEFINE ARG1 STACK_322
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_321
  DEFINE ARG1 STACK_321
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_320
  DEFINE ARG1 STACK_320
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_319
  DEFINE ARG1 STACK_319
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_318
  DEFINE ARG1 STACK_318
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_317
  DEFINE ARG1 STACK_317
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_316
  DEFINE ARG1 STACK_316
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_315
  DEFINE ARG1 STACK_315
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_314
  DEFINE ARG1 STACK_314
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_313
  DEFINE ARG1 STACK_313
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_312
  DEFINE ARG1 STACK_312
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_311
  DEFINE ARG1 STACK_311
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_310
  DEFINE ARG1 STACK_310
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_309
  DEFINE ARG1 STACK_309
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_308
  DEFINE ARG1 STACK_308
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_307
  DEFINE ARG1 STACK_307
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_306
  DEFINE ARG1 STACK_306
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_305
  DEFINE ARG1 STACK_305
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_304
  DEFINE ARG1 STACK_304
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_303
  DEFINE ARG1 STACK_303
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_302
  DEFINE ARG1 STACK_302
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_301
  DEFINE ARG1 STACK_301
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_300
  DEFINE ARG1 STACK_300
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_299
  DEFINE ARG1 STACK_299
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_298
  DEFINE ARG1 STACK_298
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_297
  DEFINE ARG1 STACK_297
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_296
  DEFINE ARG1 STACK_296
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_295
  DEFINE ARG1 STACK_295
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_294
  DEFINE ARG1 STACK_294
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_293
  DEFINE ARG1 STACK_293
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_292
  DEFINE ARG1 STACK_292
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_291
  DEFINE ARG1 STACK_291
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_290
  DEFINE ARG1 STACK_290
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_289
  DEFINE ARG1 STACK_289
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_288
  DEFINE ARG1 STACK_288
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_287
  DEFINE ARG1 STACK_287
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_286
  DEFINE ARG1 STACK_286
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_285
  DEFINE ARG1 STACK_285
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_284
  DEFINE ARG1 STACK_284
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_283
  DEFINE ARG1 STACK_283
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_282
  DEFINE ARG1 STACK_282
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_281
  DEFINE ARG1 STACK_281
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_280
  DEFINE ARG1 STACK_280
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_279
  DEFINE ARG1 STACK_279
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_278
  DEFINE ARG1 STACK_278
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_277
  DEFINE ARG1 STACK_277
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_276
  DEFINE ARG1 STACK_276
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_275
  DEFINE ARG1 STACK_275
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_274
  DEFINE ARG1 STACK_274
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_273
  DEFINE ARG1 STACK_273
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_272
  DEFINE ARG1 STACK_272
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_271
  DEFINE ARG1 STACK_271
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_270
  DEFINE ARG1 STACK_270
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_269
  DEFINE ARG1 STACK_269
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_268
  DEFINE ARG1 STACK_268
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_267
  DEFINE ARG1 STACK_267
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_266
  DEFINE ARG1 STACK_266
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_265
  DEFINE ARG1 STACK_265
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_264
  DEFINE ARG1 STACK_264
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_263
  DEFINE ARG1 STACK_263
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_262
  DEFINE ARG1 STACK_262
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_261
  DEFINE ARG1 STACK_261
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_260
  DEFINE ARG1 STACK_260
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_259
  DEFINE ARG1 STACK_259
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_258
  DEFINE ARG1 STACK_258
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_257
  DEFINE ARG1 STACK_257
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_256
  DEFINE ARG1 STACK_256
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_255
  DEFINE ARG1 STACK_255
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_254
  DEFINE ARG1 STACK_254
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_253
  DEFINE ARG1 STACK_253
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_252
  DEFINE ARG1 STACK_252
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_251
  DEFINE ARG1 STACK_251
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_250
  DEFINE ARG1 STACK_250
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_249
  DEFINE ARG1 STACK_249
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_248
  DEFINE ARG1 STACK_248
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_247
  DEFINE ARG1 STACK_247
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_246
  DEFINE ARG1 STACK_246
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_245
  DEFINE ARG1 STACK_245
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_244
  DEFINE ARG1 STACK_244
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_243
  DEFINE ARG1 STACK_243
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_242
  DEFINE ARG1 STACK_242
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_241
  DEFINE ARG1 STACK_241
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_240
  DEFINE ARG1 STACK_240
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_239
  DEFINE ARG1 STACK_239
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_238
  DEFINE ARG1 STACK_238
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_237
  DEFINE ARG1 STACK_237
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_236
  DEFINE ARG1 STACK_236
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_235
  DEFINE ARG1 STACK_235
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_234
  DEFINE ARG1 STACK_234
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_233
  DEFINE ARG1 STACK_233
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_232
  DEFINE ARG1 STACK_232
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_231
  DEFINE ARG1 STACK_231
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_230
  DEFINE ARG1 STACK_230
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_229
  DEFINE ARG1 STACK_229
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_228
  DEFINE ARG1 STACK_228
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_227
  DEFINE ARG1 STACK_227
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_226
  DEFINE ARG1 STACK_226
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_225
  DEFINE ARG1 STACK_225
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_224
  DEFINE ARG1 STACK_224
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_223
  DEFINE ARG1 STACK_223
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_222
  DEFINE ARG1 STACK_222
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_221
  DEFINE ARG1 STACK_221
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_220
  DEFINE ARG1 STACK_220
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_219
  DEFINE ARG1 STACK_219
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_218
  DEFINE ARG1 STACK_218
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_217
  DEFINE ARG1 STACK_217
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_216
  DEFINE ARG1 STACK_216
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_215
  DEFINE ARG1 STACK_215
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_214
  DEFINE ARG1 STACK_214
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_213
  DEFINE ARG1 STACK_213
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_212
  DEFINE ARG1 STACK_212
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_211
  DEFINE ARG1 STACK_211
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_210
  DEFINE ARG1 STACK_210
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_209
  DEFINE ARG1 STACK_209
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_208
  DEFINE ARG1 STACK_208
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_207
  DEFINE ARG1 STACK_207
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_206
  DEFINE ARG1 STACK_206
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_205
  DEFINE ARG1 STACK_205
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_204
  DEFINE ARG1 STACK_204
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_203
  DEFINE ARG1 STACK_203
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_202
  DEFINE ARG1 STACK_202
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_201
  DEFINE ARG1 STACK_201
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_200
  DEFINE ARG1 STACK_200
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_199
  DEFINE ARG1 STACK_199
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_198
  DEFINE ARG1 STACK_198
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_197
  DEFINE ARG1 STACK_197
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_196
  DEFINE ARG1 STACK_196
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_195
  DEFINE ARG1 STACK_195
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_194
  DEFINE ARG1 STACK_194
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_193
  DEFINE ARG1 STACK_193
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_192
  DEFINE ARG1 STACK_192
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_191
  DEFINE ARG1 STACK_191
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_190
  DEFINE ARG1 STACK_190
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_189
  DEFINE ARG1 STACK_189
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_188
  DEFINE ARG1 STACK_188
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_187
  DEFINE ARG1 STACK_187
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_186
  DEFINE ARG1 STACK_186
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_185
  DEFINE ARG1 STACK_185
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_184
  DEFINE ARG1 STACK_184
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_183
  DEFINE ARG1 STACK_183
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_182
  DEFINE ARG1 STACK_182
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_181
  DEFINE ARG1 STACK_181
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_180
  DEFINE ARG1 STACK_180
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_179
  DEFINE ARG1 STACK_179
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_178
  DEFINE ARG1 STACK_178
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_177
  DEFINE ARG1 STACK_177
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_176
  DEFINE ARG1 STACK_176
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_175
  DEFINE ARG1 STACK_175
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_174
  DEFINE ARG1 STACK_174
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_173
  DEFINE ARG1 STACK_173
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_172
  DEFINE ARG1 STACK_172
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_171
  DEFINE ARG1 STACK_171
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_170
  DEFINE ARG1 STACK_170
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_169
  DEFINE ARG1 STACK_169
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_168
  DEFINE ARG1 STACK_168
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_167
  DEFINE ARG1 STACK_167
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_166
  DEFINE ARG1 STACK_166
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_165
  DEFINE ARG1 STACK_165
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_164
  DEFINE ARG1 STACK_164
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_163
  DEFINE ARG1 STACK_163
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_162
  DEFINE ARG1 STACK_162
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_161
  DEFINE ARG1 STACK_161
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_160
  DEFINE ARG1 STACK_160
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_159
  DEFINE ARG1 STACK_159
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_158
  DEFINE ARG1 STACK_158
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_157
  DEFINE ARG1 STACK_157
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_156
  DEFINE ARG1 STACK_156
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_155
  DEFINE ARG1 STACK_155
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_154
  DEFINE ARG1 STACK_154
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_153
  DEFINE ARG1 STACK_153
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_152
  DEFINE ARG1 STACK_152
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_151
  DEFINE ARG1 STACK_151
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_150
  DEFINE ARG1 STACK_150
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_149
  DEFINE ARG1 STACK_149
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_148
  DEFINE ARG1 STACK_148
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_147
  DEFINE ARG1 STACK_147
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_146
  DEFINE ARG1 STACK_146
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_145
  DEFINE ARG1 STACK_145
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_144
  DEFINE ARG1 STACK_144
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_143
  DEFINE ARG1 STACK_143
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_142
  DEFINE ARG1 STACK_142
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_141
  DEFINE ARG1 STACK_141
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_140
  DEFINE ARG1 STACK_140
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_139
  DEFINE ARG1 STACK_139
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_138
  DEFINE ARG1 STACK_138
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_137
  DEFINE ARG1 STACK_137
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_136
  DEFINE ARG1 STACK_136
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_135
  DEFINE ARG1 STACK_135
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_134
  DEFINE ARG1 STACK_134
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_133
  DEFINE ARG1 STACK_133
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_132
  DEFINE ARG1 STACK_132
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_131
  DEFINE ARG1 STACK_131
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_130
  DEFINE ARG1 STACK_130
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_129
  DEFINE ARG1 STACK_129
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_128
  DEFINE ARG1 STACK_128
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_127
  DEFINE ARG1 STACK_127
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_126
  DEFINE ARG1 STACK_126
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_125
  DEFINE ARG1 STACK_125
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_124
  DEFINE ARG1 STACK_124
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_123
  DEFINE ARG1 STACK_123
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_122
  DEFINE ARG1 STACK_122
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_121
  DEFINE ARG1 STACK_121
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_120
  DEFINE ARG1 STACK_120
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_119
  DEFINE ARG1 STACK_119
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_118
  DEFINE ARG1 STACK_118
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_117
  DEFINE ARG1 STACK_117
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_116
  DEFINE ARG1 STACK_116
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_115
  DEFINE ARG1 STACK_115
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_114
  DEFINE ARG1 STACK_114
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_113
  DEFINE ARG1 STACK_113
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_112
  DEFINE ARG1 STACK_112
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_111
  DEFINE ARG1 STACK_111
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_110
  DEFINE ARG1 STACK_110
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_109
  DEFINE ARG1 STACK_109
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_108
  DEFINE ARG1 STACK_108
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_107
  DEFINE ARG1 STACK_107
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_106
  DEFINE ARG1 STACK_106
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_105
  DEFINE ARG1 STACK_105
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_104
  DEFINE ARG1 STACK_104
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_103
  DEFINE ARG1 STACK_103
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_102
  DEFINE ARG1 STACK_102
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_101
  DEFINE ARG1 STACK_101
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_100
  DEFINE ARG1 STACK_100
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_99
  DEFINE ARG1 STACK_99
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_98
  DEFINE ARG1 STACK_98
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_97
  DEFINE ARG1 STACK_97
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_96
  DEFINE ARG1 STACK_96
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_95
  DEFINE ARG1 STACK_95
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_94
  DEFINE ARG1 STACK_94
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_93
  DEFINE ARG1 STACK_93
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_92
  DEFINE ARG1 STACK_92
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_91
  DEFINE ARG1 STACK_91
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_90
  DEFINE ARG1 STACK_90
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_89
  DEFINE ARG1 STACK_89
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_88
  DEFINE ARG1 STACK_88
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_87
  DEFINE ARG1 STACK_87
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_86
  DEFINE ARG1 STACK_86
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_85
  DEFINE ARG1 STACK_85
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_84
  DEFINE ARG1 STACK_84
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_83
  DEFINE ARG1 STACK_83
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_82
  DEFINE ARG1 STACK_82
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_81
  DEFINE ARG1 STACK_81
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_80
  DEFINE ARG1 STACK_80
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_79
  DEFINE ARG1 STACK_79
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_78
  DEFINE ARG1 STACK_78
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_77
  DEFINE ARG1 STACK_77
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_76
  DEFINE ARG1 STACK_76
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_75
  DEFINE ARG1 STACK_75
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_74
  DEFINE ARG1 STACK_74
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_73
  DEFINE ARG1 STACK_73
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_72
  DEFINE ARG1 STACK_72
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_71
  DEFINE ARG1 STACK_71
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_70
  DEFINE ARG1 STACK_70
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_69
  DEFINE ARG1 STACK_69
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_68
  DEFINE ARG1 STACK_68
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_67
  DEFINE ARG1 STACK_67
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_66
  DEFINE ARG1 STACK_66
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_65
  DEFINE ARG1 STACK_65
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_64
  DEFINE ARG1 STACK_64
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_63
  DEFINE ARG1 STACK_63
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_62
  DEFINE ARG1 STACK_62
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_61
  DEFINE ARG1 STACK_61
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_60
  DEFINE ARG1 STACK_60
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_59
  DEFINE ARG1 STACK_59
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_58
  DEFINE ARG1 STACK_58
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_57
  DEFINE ARG1 STACK_57
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_56
  DEFINE ARG1 STACK_56
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_55
  DEFINE ARG1 STACK_55
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_54
  DEFINE ARG1 STACK_54
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_53
  DEFINE ARG1 STACK_53
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_52
  DEFINE ARG1 STACK_52
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_51
  DEFINE ARG1 STACK_51
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_50
  DEFINE ARG1 STACK_50
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_49
  DEFINE ARG1 STACK_49
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_48
  DEFINE ARG1 STACK_48
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_47
  DEFINE ARG1 STACK_47
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_46
  DEFINE ARG1 STACK_46
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_45
  DEFINE ARG1 STACK_45
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_44
  DEFINE ARG1 STACK_44
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_43
  DEFINE ARG1 STACK_43
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_42
  DEFINE ARG1 STACK_42
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_41
  DEFINE ARG1 STACK_41
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_40
  DEFINE ARG1 STACK_40
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_39
  DEFINE ARG1 STACK_39
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_38
  DEFINE ARG1 STACK_38
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_37
  DEFINE ARG1 STACK_37
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_36
  DEFINE ARG1 STACK_36
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_35
  DEFINE ARG1 STACK_35
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_34
  DEFINE ARG1 STACK_34
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_33
  DEFINE ARG1 STACK_33
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_32
  DEFINE ARG1 STACK_32
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_31
  DEFINE ARG1 STACK_31
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_30
  DEFINE ARG1 STACK_30
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_29
  DEFINE ARG1 STACK_29
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_28
  DEFINE ARG1 STACK_28
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_27
  DEFINE ARG1 STACK_27
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_26
  DEFINE ARG1 STACK_26
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_25
  DEFINE ARG1 STACK_25
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_24
  DEFINE ARG1 STACK_24
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_23
  DEFINE ARG1 STACK_23
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_22
  DEFINE ARG1 STACK_22
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_21
  DEFINE ARG1 STACK_21
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_20
  DEFINE ARG1 STACK_20
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_19
  DEFINE ARG1 STACK_19
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_18
  DEFINE ARG1 STACK_18
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_17
  DEFINE ARG1 STACK_17
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_16
  DEFINE ARG1 STACK_16
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_15
  DEFINE ARG1 STACK_15
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_14
  DEFINE ARG1 STACK_14
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_13
  DEFINE ARG1 STACK_13
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_12
  DEFINE ARG1 STACK_12
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_11
  DEFINE ARG1 STACK_11
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_10
  DEFINE ARG1 STACK_10
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_9
  DEFINE ARG1 STACK_9
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_8
  DEFINE ARG1 STACK_8
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_7
  DEFINE ARG1 STACK_7
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_6
  DEFINE ARG1 STACK_6
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_5
  DEFINE ARG1 STACK_5
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_4
  DEFINE ARG1 STACK_4
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_3
  DEFINE ARG1 STACK_3
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_2
  DEFINE ARG1 STACK_2
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_1
  DEFINE ARG1 STACK_1
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_0
  DEFINE ARG1 STACK_0
  DEFINE ARG2 ITEM
  INCLUDE "movb.h"
ELSE
ERROR Stack overflow
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
END
