/*
  Inputs: ITEM
  Pushes the bit ITEM onto the stack.
*/
#include "util.h"
IFNDEF STACK_9
  DEFINE ARG1() STACK_9
  DEFINE ARG2() ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_8
  DEFINE ARG1() STACK_8
  DEFINE ARG2() ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_7
  DEFINE ARG1() STACK_7
  DEFINE ARG2() ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_6
  DEFINE ARG1() STACK_6
  DEFINE ARG2() ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_5
  DEFINE ARG1() STACK_5
  DEFINE ARG2() ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_4
  DEFINE ARG1() STACK_4
  DEFINE ARG2() ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_3
  DEFINE ARG1() STACK_3
  DEFINE ARG2() ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_2
  DEFINE ARG1() STACK_2
  DEFINE ARG2() ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_1
  DEFINE ARG1() STACK_1
  DEFINE ARG2() ITEM
  INCLUDE "movb.h"
ELSE
IFNDEF STACK_0
  DEFINE ARG1() STACK_0
  DEFINE ARG2() ITEM
  INCLUDE "movb.h"
ELSE
  ERROR Stack overflow
END
END
END
END
END
END
END
END
END
END
